services:
  postgres:
    image: postgres:16
    container_name: books-manager-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: books-manager-redis
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: books-manager-keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/books-manager-realm.json:ro


volumes:
  pgdata: