package com.example.demo.service;

import com.example.demo.dto.request.BookSearchDTO;
import com.example.demo.exception.BookNotFoundException;
import com.example.demo.model.Book;
import com.example.demo.model.BookIsbnPolicy;
import com.example.demo.repository.BookRepository;
import com.example.demo.repository.specification.dtoToSpecBuilderUtil.DTOToSpecBuilder;
import lombok.RequiredArgsConstructor;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.CachePut;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

// @Service — marks this as a Spring-managed service bean (specialization of @Component)
// @RequiredArgsConstructor — Lombok: generates constructor for all `final` fields (dependency injection)
@Service
@RequiredArgsConstructor
public class BookService {

    // Injected by Spring via constructor (generated by @RequiredArgsConstructor)
    private final BookRepository bookRepository;

    public List<Book> getAllBooks() {
        return bookRepository.findAll();
    }

    /**
     * Dynamic multi-criteria search using JPA Specifications.
     *
     * <p>Builds a WHERE clause dynamically: only non-null fields in the DTO become
     * active filters, chained with AND. If all fields are null, returns all books.</p>
     *
     * <p>Replaces the old approach of a single {@code Topic} filter parameter —
     * previously this method was: {@code searchBooks(Topic topic, Pageable pageable)}
     * with an if/else that called either {@code findByTopic()} or {@code findAll()}.</p>
     *
     * @param bookSearchDTO filter criteria — all fields optional (null = ignored)
     * @param pageable      pagination/sort parameters (page, size, sort)
     * @return a Page containing matched books and metadata (totalElements, totalPages, etc.)
     */
    // Old approach — manual if/null checks for each filter field:
    // public Page<Book> searchBooks(BookSearchDTO bookSearchDTO, Pageable pageable) {
    //     Specification<Book> spec = Specification.unrestricted();
    //     if (bookSearchDTO.getTitle() != null) {
    //         spec = spec.and(BookSpecifications.titleContains(bookSearchDTO.getTitle()));
    //     }
    //     if (bookSearchDTO.getAuthor() != null) { ... }
    //     if (bookSearchDTO.getTopic() != null) { ... }
    //     ...
    //     return bookRepository.findAll(spec, pageable);
    // }
    //
    // Second approach — BookSpecifications.fromSearchDTO() with static SPEC_MAPPINGS list:
    // public Page<Book> searchBooks(BookSearchDTO bookSearchDTO, Pageable pageable) {
    //     return bookRepository.findAll(BookSpecifications.fromSearchDTO(bookSearchDTO), pageable);
    // }
    //
    // Third approach — static utility scans @SpecFilter annotations on the DTO via reflection:
    public Page<Book> searchBooks(BookSearchDTO bookSearchDTO, Pageable pageable) {
        return bookRepository.findAll(DTOToSpecBuilder.buildAndSpecification(bookSearchDTO), pageable);
    }

    // Returns Optional<Book> — forces caller to handle "not found" case explicitly
    @Cacheable(value = "books", unless = "#result == null || !#result.isPresent()")
    public Optional<Book> getBookById(UUID id){
        return bookRepository.findById(id);
    }

    // save() does INSERT if no id, UPDATE if id exists
    public Book createBook(Book book){
        return createBook(book, BookIsbnPolicy.ISBN_NOT_AS_IDENTIFIER);
    }

    // save() does INSERT if no id, UPDATE if id exists
    public Book createBook(Book book, BookIsbnPolicy bookIsbnPolicy){
        if(bookIsbnPolicy.equals(BookIsbnPolicy.ISBN_AS_ALERNATIVE_IDENTIFIER) && book.getId() == null){
            bookRepository
                    .findByIsbn(book.getIsbn())
                    .ifPresent(exitingBook -> book.setId(exitingBook.getId()));
        }
        return bookRepository.save(book);
    }


    public List<Book> createBooks(List<Book> books){
        return createBooks(books, BookIsbnPolicy.ISBN_NOT_AS_IDENTIFIER);
    }

    public List<Book> createBooks(List<Book> books, BookIsbnPolicy bookIsbnPolicy){
        List<Book> booksToSave = books.stream()
                .peek(book -> {
                    if(bookIsbnPolicy.equals(BookIsbnPolicy.ISBN_AS_ALERNATIVE_IDENTIFIER) && book.getId() == null){
                        bookRepository
                                .findByIsbn(book.getIsbn())
                                .ifPresent(exitingBook -> book.setId(exitingBook.getId()));
                    }
                }).toList();
        return bookRepository.saveAll(booksToSave);
    }

    // Fetch-then-update pattern: find existing, update fields, save back
    // orElseThrow() unwraps Optional or throws if empty
    @CachePut(value = "books", key = "#id")
    public Book updateBook(UUID id, Book updatedBook){
        Book existing = bookRepository.findById(id)
                .orElseThrow(() -> new BookNotFoundException(id));
        existing.setTitle(updatedBook.getTitle());
        existing.setAuthor(updatedBook.getAuthor());
        existing.setIsbn(updatedBook.getIsbn());
        existing.setTopic(updatedBook.getTopic());
        existing.setTotalPages(updatedBook.getTotalPages());
        return bookRepository.save(existing);
    }

    // Fetch first to verify existence, then delete
    @CacheEvict("books")
    public void deleteBook(UUID id){
        Book book = bookRepository.findById(id)
                .orElseThrow(() -> new BookNotFoundException(id));
        bookRepository.delete(book);
    }

}
