package com.example.demo.service;

import com.example.demo.exception.BookNotFoundException;
import com.example.demo.model.Book;
import com.example.demo.model.BookIsbnPolicy;
import com.example.demo.model.Topic;
import com.example.demo.repository.BookRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.CachePut;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

// @Service — marks this as a Spring-managed service bean (specialization of @Component)
// @RequiredArgsConstructor — Lombok: generates constructor for all `final` fields (dependency injection)
@Service
@RequiredArgsConstructor
public class BookService {

    // Injected by Spring via constructor (generated by @RequiredArgsConstructor)
    private final BookRepository bookRepository;

    public List<Book> getAllBooks() {
        return bookRepository.findAll();
    }

    /**
     * Returns a paginated, sortable list of books.
     *
     * <p>Pageable carries page number, page size, and sort direction — all parsed
     * automatically from query params by Spring MVC.</p>
     *
     * @param topic topic filter, if null returns books with all topics
     * @param pageable pagination/sort parameters (page, size, sort)
     * @return a Page containing the books and metadata (totalElements, totalPages, etc.)
     */
    public Page<Book> searchBooks(Topic topic, Pageable pageable) {
        if (topic != null) {
            return bookRepository.findByTopic(topic, pageable);
        }
        return bookRepository.findAll(pageable);
    }

    // Returns Optional<Book> — forces caller to handle "not found" case explicitly
    @Cacheable(value = "books", unless = "#result == null || !#result.isPresent()")
    public Optional<Book> getBookById(UUID id){
        return bookRepository.findById(id);
    }

    // save() does INSERT if no id, UPDATE if id exists
    public Book createBook(Book book){
        return createBook(book, BookIsbnPolicy.ISBN_NOT_AS_IDENTIFIER);
    }

    // save() does INSERT if no id, UPDATE if id exists
    public Book createBook(Book book, BookIsbnPolicy bookIsbnPolicy){
        if(bookIsbnPolicy.equals(BookIsbnPolicy.ISBN_AS_ALERNATIVE_IDENTIFIER) && book.getId() == null){
            bookRepository
                    .findByIsbn(book.getIsbn())
                    .ifPresent(exitingBook -> book.setId(exitingBook.getId()));
        }
        return bookRepository.save(book);
    }


    public List<Book> createBooks(List<Book> books){
        return createBooks(books, BookIsbnPolicy.ISBN_NOT_AS_IDENTIFIER);
    }

    public List<Book> createBooks(List<Book> books, BookIsbnPolicy bookIsbnPolicy){
        List<Book> booksToSave = books.stream()
                .peek(book -> {
                    if(bookIsbnPolicy.equals(BookIsbnPolicy.ISBN_AS_ALERNATIVE_IDENTIFIER) && book.getId() == null){
                        bookRepository
                                .findByIsbn(book.getIsbn())
                                .ifPresent(exitingBook -> book.setId(exitingBook.getId()));
                    }
                }).toList();
        return bookRepository.saveAll(booksToSave);
    }

    // Fetch-then-update pattern: find existing, update fields, save back
    // orElseThrow() unwraps Optional or throws if empty
    @CachePut(value = "books", key = "#id")
    public Book updateBook(UUID id, Book updatedBook){
        Book existing = bookRepository.findById(id)
                .orElseThrow(() -> new BookNotFoundException(id));
        existing.setTitle(updatedBook.getTitle());
        existing.setAuthor(updatedBook.getAuthor());
        existing.setIsbn(updatedBook.getIsbn());
        existing.setTopic(updatedBook.getTopic());
        existing.setTotalPages(updatedBook.getTotalPages());
        return bookRepository.save(existing);
    }

    // Fetch first to verify existence, then delete
    @CacheEvict("books")
    public void deleteBook(UUID id){
        Book book = bookRepository.findById(id)
                .orElseThrow(() -> new BookNotFoundException(id));
        bookRepository.delete(book);
    }

}
